In [3]:
import numpy as np

In [ ]:
# pip install numpy

In [5]:
oneDArray = np.array([1,2,3,4,5,6])
print(oneDArray)

[1 2 3 4 5 6]


In [7]:
print(type(oneDArray))

<class 'numpy.ndarray'>


In [9]:
print(oneDArray.ndim)

1


In [11]:
twoDArray = np.array([
    [1,2,3],
    [4,5,6]
])

In [13]:
print(twoDArray)
print(twoDArray.ndim)

[[1 2 3]
 [4 5 6]]
2


In [15]:
# three dimension array
threeDArray = np.array([
    [[1,2,3], [4,5,6]],
    [[-1,-2,-3], [-4,-5,-6]]
])

print(threeDArray)

[[[ 1  2  3]
  [ 4  5  6]]

 [[-1 -2 -3]
  [-4 -5 -6]]]


In [17]:
print(twoDArray[1][0])

4


In [19]:
print(twoDArray[1,0])

4


In [21]:
print(threeDArray[0][1][0])

4


# Attributes of an array

In [24]:
# dtype
print(oneDArray.dtype)
print(twoDArray.dtype)
print(threeDArray.dtype)

int32
int32
int32


In [26]:
# shape
print(oneDArray.shape)
print(twoDArray.shape)
print(threeDArray.shape)

(6,)
(2, 3)
(2, 2, 3)


In [28]:
# size
print(oneDArray.size)
print(twoDArray.size)
print(threeDArray.size)

6
6
12


In [30]:
# itemsize
print(oneDArray.itemsize)
print(twoDArray.itemsize)
print(threeDArray.itemsize)

4
4
4


In [32]:
nested_list = [[1,2,3],[4,5,6]]

In [34]:
for i in nested_list:
    for j in i:
        print(j)

1
2
3
4
5
6


In [36]:
for i in twoDArray:
    for j in i:
        print(j)

1
2
3
4
5
6


In [38]:
for i in threeDArray.flatten():
    print(i)

1
2
3
4
5
6
-1
-2
-3
-4
-5
-6


In [40]:
threeDArray.flatten()
print(threeDArray)
threeDArray.ravel()
print(threeDArray)

[[[ 1  2  3]
  [ 4  5  6]]

 [[-1 -2 -3]
  [-4 -5 -6]]]
[[[ 1  2  3]
  [ 4  5  6]]

 [[-1 -2 -3]
  [-4 -5 -6]]]


## filling arrays with specific values

In [43]:
# zeros
zeros = np.zeros(5)
print(zeros)

[0. 0. 0. 0. 0.]


In [45]:
# ones
ones = np.ones(8)
print(ones)

[1. 1. 1. 1. 1. 1. 1. 1.]


In [47]:
ones = ones.astype(int)
print(ones)

[1 1 1 1 1 1 1 1]


In [49]:
# arange
ranges = np.arange(5.6,9.8)

In [51]:
print(ranges)

[5.6 6.6 7.6 8.6 9.6]


In [57]:
# linspace
linspace = np.linspace(3,6,10)
print(linspace)

[3.         3.33333333 3.66666667 4.         4.33333333 4.66666667
 5.         5.33333333 5.66666667 6.        ]


In [ ]:
# help(np.linspace)

# Scalar operation

In [59]:
matrix = np.array([[76,34,89], [23,34,45]])
print(matrix)

[[76 34 89]
 [23 34 45]]


In [61]:
print(matrix + 2)

[[78 36 91]
 [25 36 47]]


In [63]:
pythonlist = [[76,34,89], [23,34,45]]

In [65]:
# print(pythonlist + 2)
print(pythonlist * 2)

[[76, 34, 89], [23, 34, 45], [76, 34, 89], [23, 34, 45]]


In [67]:
# multi
print(matrix * 2)

[[152  68 178]
 [ 46  68  90]]


In [69]:
# division
print(matrix / 2)

[[38.  17.  44.5]
 [11.5 17.  22.5]]


In [71]:
# floor division
print(matrix // 2)

[[38 17 44]
 [11 17 22]]


In [73]:
# exponent
print(matrix ** 2)

[[5776 1156 7921]
 [ 529 1156 2025]]


In [75]:
print(matrix.T)

[[76 23]
 [34 34]
 [89 45]]


In [77]:
print(matrix[1,])

[23 34 45]
