In [1]:
import numpy as np

In [3]:
print("1-dimension")
full = np.full(10, 5)
print(full)

print("2-dimension")
full = np.full((2, 2), 10)
print(full)

print("3-dimension")
full = np.full((2,5,4), 5)
print(full)

1-dimension
[5 5 5 5 5 5 5 5 5 5]
2-dimension
[[10 10]
 [10 10]]
3-dimension
[[[5 5 5 5]
  [5 5 5 5]
  [5 5 5 5]
  [5 5 5 5]
  [5 5 5 5]]

 [[5 5 5 5]
  [5 5 5 5]
  [5 5 5 5]
  [5 5 5 5]
  [5 5 5 5]]]


# Element-wise operation

In [5]:
pythonlist1 = [[76,34,89], [23,34,45]]
pythonlist2 = [[76,34,89], [23,34,45]]

In [7]:
pythonlist1 + pythonlist2

[[76, 34, 89], [23, 34, 45], [76, 34, 89], [23, 34, 45]]

In [9]:
matrix1 = np.array([[1,2,3], [4,5,6]])
matrix2 = np.array([[7,8,9], [10,11,12]])

In [11]:
print(matrix1 + matrix2)

[[ 8 10 12]
 [14 16 18]]


In [13]:
print(matrix1 - matrix2)

[[-6 -6 -6]
 [-6 -6 -6]]


In [15]:
print(matrix1 * matrix2)

[[ 7 16 27]
 [40 55 72]]


# to perform matrix multiplication

In [17]:
matrix1 = np.array([[1,2,3], [4,5,6], [13,14,15]]) # 3x3
matrix2 = np.array([[7,8,9], [10,11,12], [16,17,18]]) # 3x3

print(np.matmul(matrix1,matrix2))

[[ 75  81  87]
 [174 189 204]
 [471 513 555]]


# statistical function in numpy library

In [21]:
marks = np.array([
    [87,90,89], [100,87,90],
    [94,77,90], [100, 86, 98]
])

In [23]:
print(marks.min())
print(marks.max())
print(marks.sum())
print(marks.mean())
print(marks.std())
print(round(marks.var(),2))

77
100
1088
90.66666666666667
6.315765107165473
39.89


__axis = 1 means row__

In [26]:
print(marks.min(axis = 1))
print(marks.max(axis = 1))
print(marks.sum(axis = 1))
print(marks.mean(axis = 1))
print(marks.std(axis = 1))

[87 87 77 86]
[ 90 100  94 100]
[266 277 261 284]
[88.66666667 92.33333333 87.         94.66666667]
[1.24721913 5.55777733 7.25718035 6.18241233]


__axis = 0 means columnwise__

In [28]:
print(marks.min(axis = 0))
print(marks.max(axis = 0))
print(marks.sum(axis = 0))
print(marks.mean(axis = 0))
print(marks.std(axis = 0))

[87 77 89]
[100  90  98]
[381 340 367]
[95.25 85.   91.75]
[5.35607132 4.84767986 3.63145976]


# Append

In [30]:
x = np.array([0,1,2,3,4])
y = np.array([0,1,2,3,4])
z = np.array([0,1,2,3,4])

# hstack, vstack

__hstack__

In [32]:
np.hstack([x,y,z])

array([0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4])

__vstack__

In [34]:
np.vstack([x,y,z])

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

In [36]:
np.append(x,(2,3))

array([0, 1, 2, 3, 4, 2, 3])

In [38]:
x

array([0, 1, 2, 3, 4])

In [40]:
x = np.append(x,(2,3))

In [42]:
x

array([0, 1, 2, 3, 4, 2, 3])

In [44]:
new_array = np.array([1,2,3])

In [46]:
x = np.append([[1, 2, 3], [4, 5, 6]], [[1, 2, 3], new_array], 
              axis=0)
x

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [1, 2, 3]])

In [102]:
x.ndim

2

In [48]:
np.transpose(x)

array([[1, 4, 1, 1],
       [2, 5, 2, 2],
       [3, 6, 3, 3]])

In [50]:
x.T

array([[1, 4, 1, 1],
       [2, 5, 2, 2],
       [3, 6, 3, 3]])

# Boolean indexing

In [52]:
arr = np.arange(7)
print(arr)

[0 1 2 3 4 5 6]


In [54]:
arr > 4

array([False, False, False, False, False,  True,  True])

In [56]:
arr[arr > 4]

array([5, 6])

# reshaping an array

In [58]:
array = np.arange(12)

In [122]:
array.shape = (3,4)

In [60]:
np.arange(12).reshape((2,3,2))

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]]])

In [62]:
array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [130]:
array.size

12

In [132]:
array.ndim

2

# generating random values

In [64]:
np.random.rand(5)

array([0.85725194, 0.05051379, 0.66988413, 0.28726644, 0.2120834 ])

In [66]:
np.random.randint(10,20, (5,5))

array([[16, 11, 15, 11, 11],
       [16, 13, 13, 16, 10],
       [15, 16, 16, 12, 11],
       [17, 17, 16, 19, 12],
       [16, 10, 14, 17, 14]])

In [68]:
letters = list('aeiou')
np.random.choice(letters, 13)

array(['a', 'o', 'a', 'i', 'e', 'o', 'a', 'o', 'i', 'o', 'o', 'u', 'o'],
      dtype='<U1')

In [70]:
np.random.choice(letters, 5)

array(['a', 'o', 'o', 'a', 'e'], dtype='<U1')

In [143]:
np.random.choice(letters, 5, replace=False)

array(['e', 'o', 'u', 'i', 'a'], dtype='<U1')

In [68]:
np.random.choice(letters, 15, p=[0.4, 0.3, 0.1, 0.1, 0.1])

array(['e', 'a', 'e', 'i', 'i', 'e', 'a', 'i', 'a', 'i', 'e', 'e', 'u',
       'a', 'u'], dtype='<U1')

# save and load array

In [72]:
array = np.random.randint(10,20, (5,5))
np.save('array_file', array)

In [74]:
array2 = np.load('array_file.npy')
print(array2)

[[14 17 15 16 10]
 [19 10 16 15 13]
 [11 16 19 17 16]
 [12 11 18 17 10]
 [10 17 19 19 19]]
